export const names = [
    "Martin Teelaht",
    "Rauno Eensalu & Stiina Tiitmaa",
    "Marek Karu",
    "Kaspar Kess",
    "Anna - Liisa Tumala",
    "Aide ja Glaid Traagel",
    "Liina ja Ardo Rakaselg",
    "Joonas ja Johanna Jaanovits",
    "Jaagup Jaanovits",
    "Erika Kivi",
    "Pille Amur",
    "Kristi ja Rein Kontson",
    "Toomas Krall",
    "Lauri Karu",
    "Priit “Propekas”",
    "Maigo Täpsi ja Ly Unga",
    "Silver Hints",
    "Sulev Võrno",
    "Mihkel Soolo",
    "Mihkel Lipp",
    "Madis Lindmäe",
    "Urmas Pülzu",
    "Tõnis ja Liis Paalo",
    "Kaido ja Regina Vaarpuu",
    "Urmas Laaneviir",
    "Hannela Kurvits",
    "Diana",
    "Kris Jaanhold",
    "Daire",
]