export const names = [
    "Martin Teelaht",
    "Rauno Eensalu",
    "Stiina Tiitmaa",
    "Marek Karu",
    "Kaspar Kess",
    "Anna - Liisa Tumala",
    "Aide ja Glaid Traagel",
    "Liina ja Ardo Rakaselg",
    "Johanna Jaanovits",
    "Jaagup Jaanovits",
    "Erika Kivi",
    "Pille Amur",
    "Kristi ja Rein Kontson",
    "Toomas Krall",
    "Lauri Karu",
    "Priit “Propekas”",
    "Maigo Täpsi ja Ly Unga",
    "Silver Hints",
    "Sulev Võrno",
    "Mihkel Soolo",
    "Mihkel Lipp",
    "Madis Lindmäe",
    "Urmas Pülzu",
    "Tõnis ja Liis Paalo",
    "Kaido ja Regina Vaarpuu",
    "Urmas Laaneviir",
    "Hannela Kurvits",
    "Diana",
    "Kris Jaanhold",
    "Daire",
    "Raili ja Kristo",
    "Milja",
    "Katrin ja Rauno ",
    "Merlin",
    "Maarja Kaljurand",
    "Maarja ja Tõnis ",
    "Maarja ja Joni ",
    "Liis",
    "Gelina ja Jaan",
    "Annika kaaslasega",
    "Kristel ja Andro",
    "Kadri ja Kristjan",
    "Virginia ja Ahto",
    "Diana ja Mikk",
    "Elerin ja Leino",
    "Karmen ja Jörgen",
    "Ruth ja Reimo",
    "Katrin ja Tavo ",
    "Maidu",
    "Veikko",
    "Marko",
    "Benno kaaslasega",
    "Kristin ja Argo",
    "Kaidi ja Meelis",
    "Katrin kaaslasega",
    "Greete kaaslasega",
    "Katrel kaaslasega",
    "Aino kaaslasega",
    "Merle kaaslasega",
    "Janek Veevo ja Einar Siim"
]